---
version: "2"
use_cases:
- name: default
  sections:
  - name: NodeJS Server
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "vCPU"
        unit: vCPU
        description: "Number of vCPU allocated to the virtual machine."
        key: vm_cpu
        widget: slider_range
        type: integer
        default: 2
        values:
            - 1
            - 4
        required: true
        # CPU amount will be deducted from the team quota
        quota_config:
          type: "cpu"
      - name: "Memory"
        unit: Mo
        description: "Memory allocated to the virtual machine."
        key: vm_memory
        widget: slider_list
        type: integer
        default: 2048
        values:
            - 1024
            - 2048
            - 4096
        required: true
        # Memory amount will be deducted from the team quota
        quota_config:
          type: "memory"
      - name: "Disk"
        unit: Go
        description: "Disk size allocated to the virtual machine."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 200
        required: true
        # Storage amount will be deducted from the team quota
        quota_config:
          type: "storage"
      - name: "Clone from VM or Template Name"
        description: "Virtual Machine or Template name to clone from. The VM or template must already exist in your VMware datacenter."
        key: vsphere_template
        widget: auto_complete
        type: string
        values: ["debian","ubuntu","hardened debian"]
        default: "debian"
        required: true
      - name: "IP Address"
        description: "IP address to assign to the virtual machine network interface. You can also integrate Cycloid with an IP Address Management tool."
        key: vm_ip
        widget: simple_text
        default: "212.129.18.92"
        type: string
        required: true
      - name: "MAC Address"
        description: "MAC address to assign to the virtual machine network interface. You can also integrate Cycloid with a MAC Address Management tool."
        key: vm_mac
        widget: simple_text
        default: "00:50:56:01:f1:96"
        type: string
        required: true

  # Uncomment if you want the user to be able to override the default values set in the terraform module
  #     - name: "Network"
  #       description: "Network where the virtual machine will be located."
  #       key: vsphere_network
  #       widget: simple_text
  #       default: "VM Network"
  #       type: string
  #       required: true

    - name: NodeJS Application
      technologies: [terraform]
      vars:
      - name: "Webapp Public Git URL"
        description: "Public git URL of the web application to build and deploy."
        key: git_app_url
        widget: auto_complete
        type: string
        values: ["https://github.com/Rahul-Pandey7/react-image-compressor.git","https://github.com/arnab-datta/counter-app.git","https://github.com/Yog9/SnapShot.git","https://github.com/ahfarmer/calculator.git","https://github.com/ahfarmer/emoji-search.git"]
        default: "https://github.com/Yog9/SnapShot.git"
        required: true

  - name: VMware Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "vSphere Environment"
        description: "The vSphere environment where to deploy the infrastructure. It contains server, user, password, datacenter, datastore and cluster."
        key: vsphere_env
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: "((vsphere))"

  # Uncomment if you want the user to be able to override the default values set in the pipeline
  #
  # - name: Cycloid Platform
  #   groups:
  #   - name: Cycloid API
  #     technologies: [pipeline]
  #     vars:
  #     - name: "Cycloid API URL"
  #       description: "Cycloid API URL. Leave the default value unless your are running an on premises Cycloid platform."
  #       key: cycloid_api_url
  #       widget: simple_text
  #       type: string
  #       default: "https://http-api.cycloid.io"
  #       required: true
  #     - name: "Cycloid API key"
  #       description: "API key to grant access to Cycloid API."
  #       key: cycloid_api_key
  #       widget: cy_cred
  #       type: string
  #       default: "((cycloid-api-key.key))"
  #       required: true