---
# Configuration of the Cycloid stack
version: '2'
name: 'Drupal on Kubernetes'
canonical: 'stack-drupal-k8s'
description: This stack deploys a Drupal on a Kubernetes cluster connecting to an external MySQL database.
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/drupal.png'
status: 'private'
keywords:
- drupal
- repository
- artefact
- demo
- provider:kubernetes
technologies:
- technology: drupal
  version: "n/a"

config:
  default:
    name: 'Kubernetes'
    description: 'Deploys a Drupal on a Kubernetes cluster using a Helm chart'
    # Pipeline and variable configuration for the Kubernetes pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'