---
version: "2"
use_cases:
- name: default
  sections:
  - name: Drupal
    groups:
    - name: Database Configuration
      technologies: [pipeline]
      vars:
      - name: "Database Endpoint"
        description: "Database endpoint."
        key: database_endpoint
        widget: cy_cred
        widget_config:
          cred_types:
            - custom
        type: string
        default: ((rds.endpoint))
        required: true
      - name: "Database Username"
        description: "Database username."
        key: database_username
        widget: cy_cred
        widget_config:
          cred_types:
            - custom
        type: string
        default: ((rds.username))
        required: true
      - name: "Database Password"
        description: "Database password."
        key: database_password
        widget: cy_cred
        widget_config:
          cred_types:
            - custom
        type: string
        default: ((rds.password))
        required: true
      - name: "Database name"
        description: "Database name."
        key: database_name
        widget: simple_text
        type: string
        default: "bitnami_drupal"
        required: true

    - name: Kubernetes Cluster Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Kubernetes Host"
        description: "The hostname (in form of URI) of the Kubernetes API."
        key: k8s_host
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.host))
        required: true
      - name: "Kubernetes Cluster CA Certificate"
        description: "PEM-encoded root certificates bundle for TLS authentication."
        key: k8s_cluster_ca_certificate
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.cluster_ca_certificate))
        required: true
      - name: "Kubernetes Token"
        description: "Token of your service account."
        key: k8s_token
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.token))
        required: true
      - name: "Namespace"
        description: "Namespace where to deploy the workload. The Namespace shall already exist."
        key: k8s_namespace
        widget: simple_text
        type: string
        default: ""
        required: true