---
version: "2"
use_cases:
- name: default
  sections:
  - name: Drupal
    groups:
    - name: Database Configuration
      technologies: [terraform]
      vars:
      - name: "Database Cluster"
        description: "Database Cluster and Credentials. Includes endpoint, username and password."
        key: database_cluster
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: ((rds))
        required: true
      - name: "Database name"
        description: "Database name."
        key: database_name
        widget: simple_text
        type: string
        default: "bitnami_drupal"
        required: true

    - name: Kubernetes Cluster Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Kubernetes Host"
        description: "The hostname (in form of URI) of the Kubernetes API."
        key: k8s_host
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.host))
        required: true
      - name: "Kubernetes Cluster CA Certificate"
        description: "PEM-encoded root certificates bundle for TLS authentication."
        key: k8s_cluster_ca_certificate
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.cluster_ca_certificate))
        required: true
      - name: "Kubernetes Token"
        description: "Token of your service account."
        key: k8s_token
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: ((kubernetes.token))
        required: true
      - name: "Namespace"
        description: "Namespace where to deploy the workload. The Namespace shall already exist."
        key: k8s_namespace
        widget: simple_text
        type: string
        default: ""
        required: true