apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
  namespace: staging
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2  
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: secret-manager-role
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: kubectl
            imagePullPolicy: IfNotPresent
            image: bearengineer/awscli-kubectl:latest
            command:
            - "/bin/sh"
            - "-c"
            - |
              AWS_ACCOUNT=711601140448
              AWS_REGION=us-east-1
              DOCKER_REGISTRY_SERVER=711601140448.dkr.ecr.us-east-1.amazonaws.com
              DOCKER_USER=AWS
              DOCKER_PASSWORD=`aws ecr get-login --region ${AWS_REGION} --registry-ids ${AWS_ACCOUNT} | cut -d' ' -f6`

              kubectl delete secret regcred || true
              kubectl create secret docker-registry regcred \
              --docker-server=$DOCKER_REGISTRY_SERVER \
              --docker-username=$DOCKER_USER \
              --docker-password=$DOCKER_PASSWORD \
              --docker-email=no@email.local

              kubectl patch serviceaccount secret-manager-role -n staging -p '{"imagePullSecrets":[{"name":"regcred"}]}'
