resource_types:
  - name: api-call
    type: docker-image
    source:
      repository: jgriff/http-resource

resources:
  # - name: github-org-repo
  #   type: api-call
  #   source:
  #     url: https://api.github.com/orgs/((github-org))/repos
  #     headers:
  #       Accept: application/vnd.github+json
  #       X-GitHub-Api-Version: 2022-11-28
  #       Authorization: Bearer ((github-token))
  #     version:
  #       jq: .id
  #       default: none

  - name: github-user-repo
    type: api-call
    source:
      url: https://api.github.com/user/repos
      # out_only: true
      headers:
        Accept: application/vnd.github+json
        X-GitHub-Api-Version: '2022-11-28'
        Authorization: Bearer ((github-token))
      version:
        jq: .id
        jq: '.[] | select(.name=="((repo_name))")' 
        hash: body

groups:
- name: overview
  jobs:
    - github-repo

jobs:
  - name: github-repo
    plan:
      - put: github-user-repo
        params:
          text: |
            {"name":"((repo_name))","description":"((repo_description))","private":true,"is_template":false}

        
      - task: take-a-look
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: github-user-repo
          run:
            path: cat
            args: ["github-user-repo/headers", "github-user-repo/body"]