---
version: "2"
use_cases:
- name: default
  sections:
  - name: AWS Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS access key"
        description: "Amazon AWS access key used to deploy the infrastructure."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
        required: true
      - name: "AWS secret key"
        description: "Amazon AWS secret key used to deploy the infrastructure."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
        required: true
      # - name: "AWS account"
      #   description: "The AWS account where to deploy the infrastructure."
      #   key: aws_cred
      #   widget: cy_cred
      #   widget_config:
      #     display_keys: false
      #     cred_types:
      #       - aws
      #   type: string
      #   default: "((aws))"
      #   required: true
      - name: Subnet
        description: Subnet where to deploy the instance.
        key: aws_subnet
        widget: auto_complete
        type: string
        default: ""
        values:
          options:
            - name: "Subnets for AWS Dev Account"
              condition: "$aws_access_key == 'AKIAV7HNTHE3IZKYVLPE'"
              values:
                - "subnet-0866446def6d05a3f"
                - "subnet-05eceba7d6447a365"
            - name: "Subnets for AWS Training Account"
              condition: "$aws_access_key == 'AKIASW66ALRMHBEZT2G4'"
              values:
                - "subnet-0b89b11a8b1662386"
                - "subnet-017d7411b3a2e5c15"
                - "subnet-0a74cdafc53078ca4"
        required: true

  - name: EC2 Instance
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "t3a.small"
        values:
            - "t3a.small"
            - "t3a.medium"
            - "t3a.large"
        required: true
      - name: "Instance volume size"
        unit: Go
        description: "Disk size for the VM."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 8
            - 100
        required: true
      - name: "Instance AMI"
        description: "Instance AMI for the VM."
        key: vm_instance_ami
        widget: radios
        type: map
        default: "Amazon Linux"
        values:
          - {label: "Amazon Linux", value: "ami-02396cdd13e9a1257"}
          - {label: "Debian 11", value: "ami-0fec2c2e2017f4e7b"}
          - {label: "Microsoft Windows Server 2022", value: "ami-0bde1eb2c18cb2abe"}
        required: true