---
version: "2"
use_cases:
- name: default
  sections:
  - name: Harbor registry
    groups:
    - name: Pod specifications
      technologies: [terraform]
      vars:
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Harbor Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 250
        required: true
    - name: Application Configuration
      technologies: [terraform]
      vars:
      - name: "Port"
        description: "Port where Harbor Repository service is exposed."
        key: harbor_port
        widget: simple_text
        type: string
        default: "8081"
        required: true

  - name: AWS Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true

    - name: EKS Kubernetes Cluster Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Cluster Name"
        description: "Cluster name where to deploy the workload. The Kubernetes cluster shall exist or be created beforehand."
        key: eks_cluster_name
        widget: simple_text
        type: string
        default: default
        required: true
      - name: "Namespace"
        description: "Namespace where to deploy the workload. The Namespace will be created."
        key: eks_namespace
        widget: simple_text
        type: string
        default: harbor-poc
        required: true