version: "2"
name: Child organization
canonical: stack-child-org
status: private
author: Cycloid
description: |
  Creates a child Cycloid organization.
image: |
  https://console.cycloid.io/static/images/app-logo-square.png
keywords:
  - cycloid
  - organization
technologies:
  - technology: cycloid

config:
  default:
    name: 'Default'
    description: 'Creates a child Cycloid organization'
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ project $)/pipeline/($ environment $)/variables.yaml