---
version: "2"
use_cases:
- name: default
  sections:
  - name: GitHub
    groups:
    - name: GitHub Organization
      technologies: [pipeline]
      vars:
      - name: "GitHub Organization"
        description: "GitHub Organization."
        key: github-org
        widget: simple_text
        type: string
        default: ""
        required: true