---
# Configuration of the Cycloid stack
version: '2'
name: 'Harbor on Kubernetes'
canonical: 'stack-harbor-k8s'
description: This stack deploys a Harbor open source registry on a Kubernetes cluster connecting to an external Postgres database.
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/harbor.png'
status: 'private'
keywords:
- harbor
- repository
- artefact
- demo
technologies:
- technology: harbor
  version: "2.7.0"

config:
  default:
    name: 'Kubernetes'
    description: 'Deploys a Harbor open source registry on a Kubernetes cluster using a Helm chart'
    # Pipeline and variable configuration for the Kubernetes pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'