---
version: "2"
use_cases:
- name: default
  sections:
  - name: Harbor Registry
    groups:
    - name: Database Configuration
      technologies: [terraform]
      vars:
      - name: "Database Cluster"
        description: "Database Cluster and Credentials. Includes endpoint, username and password."
        key: database_cluster
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: ((rds))
        required: true
      - name: "Core Database name"
        description: "Core Database name."
        key: database_coreDatabase
        widget: simple_text
        type: string
        default: "registry"
        required: true
      - name: "Notary Server Database name"
        description: "Notary Server Database name."
        key: database_notaryServerDatabase
        widget: simple_text
        type: string
        default: "notary_server"
        required: true
      - name: "Notary Signer Database name"
        description: "Notary Signer Database name."
        key: database_notarySignerDatabase
        widget: simple_text
        type: string
        default: "notary_signer"
        required: true

    - name: Kubernetes Cluster Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Kubernetes Cluster"
        description: "Kubernetes Cluster and Credentials. Includes host, cluster_ca_certificate and token."
        key: k8s_cluster
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - custom
        type: string
        default: ((kubernetes))
        required: true
      - name: "Namespace"
        description: "Namespace where to deploy the workload. The Namespace shall already exist."
        key: k8s_namespace
        widget: simple_text
        type: string
        default: ""
        required: true