---
version: "2"
use_cases:
- name: default
  sections:
  - name: Harbor Registry
    groups:
    - name: Database Configuration
      technologies: [terraform]
      vars:
      - name: "Database Cluster"
        description: "Database Cluster and Credentials."
        key: database_cluster
        widget: cy_cred
        type: string
        default: ((rds))
        required: true
      - name: "Core Database name"
        description: "Core Database name."
        key: database_coreDatabase
        widget: simple_text
        type: string
        default: "registry"
        required: true
      - name: "Notary Server Database name"
        description: "Notary Server Database name."
        key: database_notaryServerDatabase
        widget: simple_text
        type: string
        default: "notary_server"
        required: true
      - name: "Notary Signer Database name"
        description: "Notary Signer Database name."
        key: database_notarySignerDatabase
        widget: simple_text
        type: string
        default: "notary_signer"
        required: true

    - name: Kubernetes Cluster Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Kubernetes Hostname"
        description: "The hostname (in form of URI) of the Kubernetes API where to deploy the workload."
        key: k8s_host
        type: string
        widget: simple_text
        default: ""
        required: true
      - name: "Kubernetes Cluster CA Certificate"
        description: "PEM-encoded root certificates bundle for TLS authentication."
        key: k8s_cluster_ca_certificate
        type: string
        widget: simple_text
        default: ""
        required: true
      - name: "Kubernetes Service Account Token"
        description: "Token of your service account."
        key: k8s_token
        type: string
        widget: simple_text
        default: ""
        required: true
      - name: "Namespace"
        description: "Namespace where to deploy the workload. The Namespace shall already exist."
        key: k8s_namespace
        widget: simple_text
        type: string
        default: ""
        required: true