---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: staging
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: 711601140448.dkr.ecr.us-east-1.amazonaws.com/certifai-125-eks-dev-repository:latest
        name: echoserver
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: staging
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - demo.certifai-125-eks.insights.ai
    secretName: foo-api-secret
  rules:
  - host: demo.certifai-125-eks.insights.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 8080
