resources:
  - name: pulumi-code
    type: git
    icon: git
    source:
      uri: ((git_pulumi_repository))
      branch: ((git_pulumi_branch))
      private_key: ((git_pulumi_private_key))
      paths:
        - ((git_pulumi_path))/*
jobs:
  - name: pulumi-preview
    plan:
      - get: pulumi-code
      - config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/poc-pulumi-runner
              tag: nodejs-latest
          run:
            path: /entrypoint.sh
          inputs:
            - name: pulumi-code
          outputs:
            - name: pulumi-code
        params:
          ARM_CLIENT_ID: ((((azure_cred)).client_id))
          ARM_CLIENT_SECRET: ((((azure_cred)).client_secret))
          ARM_SUBSCRIPTION_ID: ((((azure_cred)).subscription_id))
          ARM_TENANT_ID: ((((azure_cred)).tenant_id))
          PULUMI_ACCESS_TOKEN: ((pulumi.token))
          PULUMI_CODE_BUILD: 'true'
          PULUMI_CODE_BUILD_CMD: npm ci
          PULUMI_CODE_PATH: pulumi-code/((git_pulumi_path))
          PULUMI_COMMAND: preview
          PULUMI_CONFIG: '{"azure-native:location":"westeurope"}'
          PULUMI_ORG: ((pulumi_org))
          PULUMI_PROJECT: ((pulumi_project))
          PULUMI_STACK: ((pulumi_stack))
        task: pulumi-preview
  - name: pulumi-up
    plan:
      - get: pulumi-code
      - config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/poc-pulumi-runner
              tag: nodejs-latest
          run:
            path: /entrypoint.sh
          inputs:
            - name: pulumi-code
          outputs:
            - name: pulumi-code
        params:
          ARM_CLIENT_ID: ((((azure_cred)).client_id))
          ARM_CLIENT_SECRET: ((((azure_cred)).client_secret))
          ARM_SUBSCRIPTION_ID: ((((azure_cred)).subscription_id))
          ARM_TENANT_ID: ((((azure_cred)).tenant_id))
          PULUMI_ACCESS_TOKEN: ((pulumi.token))
          PULUMI_CODE_BUILD: 'true'
          PULUMI_CODE_BUILD_CMD: npm ci
          PULUMI_CODE_PATH: pulumi-code/((git_pulumi_path))
          PULUMI_COMMAND: up
          PULUMI_CONFIG: '{"azure-native:location":"westeurope"}'
          PULUMI_ORG: ((pulumi_org))
          PULUMI_PROJECT: ((pulumi_project))
          PULUMI_STACK: ((pulumi_stack))
        task: pulumi-up
  - name: pulumi-destroy
    plan:
      - get: pulumi-code
      - config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/poc-pulumi-runner
              tag: nodejs-latest
          run:
            path: /entrypoint.sh
          inputs:
            - name: pulumi-code
          outputs:
            - name: pulumi-code
        params:
          ARM_CLIENT_ID: ((((azure_cred)).client_id))
          ARM_CLIENT_SECRET: ((((azure_cred)).client_secret))
          ARM_SUBSCRIPTION_ID: ((((azure_cred)).subscription_id))
          ARM_TENANT_ID: ((((azure_cred)).tenant_id))
          PULUMI_ACCESS_TOKEN: ((pulumi.token))
          PULUMI_CODE_BUILD: 'true'
          PULUMI_CODE_BUILD_CMD: npm ci
          PULUMI_CODE_PATH: pulumi-code/((git_pulumi_path))
          PULUMI_COMMAND: destroy
          PULUMI_CONFIG: '{"azure-native:location":"((azure_location))"}'
          PULUMI_ORG: ((pulumi_org))
          PULUMI_PROJECT: ((pulumi_project))
          PULUMI_STACK: ((pulumi_stack))
        task: pulumi-destroy