---
version: "2"
use_cases:
- name: default
  sections:
  - name: Auto-Scaling Wordpress
    groups:
    - name: AWS Cloud Provider
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
      - name: "AWS region"
        description: "Amazon AWS region where to deploy the infrastructure."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true

    - name: RDS Instance specifications
      technologies: [terraform]
      vars:
      - name: "RDS Instance class"
        description: "Instance class for the RDS cluster."
        key: module.rds.rds_instance_class
        widget: slider_list
        type: string
        default: "db.t3.medium"
        values:
            - "db.t3.small"
            - "db.t3.medium"
            - "db.t3.large"
        required: true
      - name: "Allocated Storage"
        unit: Go
        description: "Allocated storage for the RDS service."
        key: module.rds.rds_allocated_storage
        widget: slider_range
        type: integer
        default: 32
        values:
            - 32
            - 250
        required: true

    - name: Auto Scaling Group 
      technologies: [terraform]
      vars:
      - name: "AMI ID"
        description: "AMI ID for the ASG."
        key: module.asg.asg_ami_id
        widget: simple_text
        type: string
        default: "ami-082a12a990b3012f3"
        required: true
      - name: "Instance Type"
        description: "Instance types to use in the ASG."
        key: module.asg.asg_instance_type
        widget: slider_list
        type: string
        default: "t3a.small"
        values:
            - "t3a.small"
            - "t3a.medium"
            - "t3a.large"
        required: true
      - name: "Minimum Size"
        description: "Minimum size for the ALB."
        key: module.asg.asg_min_size
        widget: slider_range
        type: integer
        default: 1
        values:
            - 1
            - 4
        required: true
      - name: "Maximum Size"
        description: "Maximum size for the ALB."
        key: module.asg.asg_max_size
        widget: slider_range
        type: integer
        default: 3
        values:
            - 1
            - 4
        required: true
      - name: "Desired Capacity"
        description: "Desired capacity for the ALB."
        key: module.asg.asg_desired_capacity
        widget: slider_range
        type: integer
        default: 1
        values:
            - 1
            - 4
        required: true
