---
# Configuration of the Cycloid stack
version: '2'
name: 'Nexus Repository with role'
canonical: 'stack-westrock-nexus'
description: This stack deploys a Nexus Repository on AWS using Terraform and Ansible. A role allowing to create an EC2 instance, VPC and subnets as well as reading the S3 bucket where the Terraform state files are stores will need to be attached to the Cycloid worker.
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/nexus.png'
status: 'private'
keywords:
- nexus
- repository
- artefact
- provider:aws
technologies:
- technology: nexus
  version: "3.33"

config:
  aws:
    name: 'AWS'
    description: 'Deploys a Nexus Repository in a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/aws/pipeline.yml'
      variables:
        path: 'pipeline/aws/variables.sample.yml'
        destination: '($ project $)/pipeline/aws/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      nexus:
        path: 'ansible/environments/nexus.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-nexus.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ project $)/terraform/aws/($ environment $)/main.tf'
