---
# Configuration of the Cycloid stack
version: '2'
name: 'Nexus Repository on AKS'
canonical: 'stack-nexus-aks'
description: This stack deploys a Nexus Repository on an Azure Kubernetes Service (AKS) cluster.
author: 'Olivier de Turckheim'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/nexus.png'
status: 'private'
keywords:
- nexus
- repository
- artefact
- provider:azure
technologies:
- technology: nexus
  version: "3.33"

config:
  default:
    name: 'Deploys Nexus Repository on AKS'
    description: 'Deploys a Nexus Repository in a Azure AKS Kubernetes cluster using a Helm chart via Terraform'
    # Pipeline and variable configuration for the Kubernetes pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
