version: "2"
name: Cycloid Organization
canonical: stack-cycloid-org
status: private
author: Cycloid
description: |
  Creates a Cycloid organization and set it up.
image: |
  https://console.cycloid.io/static/images/app-logo-square.png
keywords:
  - cycloid
  - organization
technologies:
  - technology: cycloid

config:
  default:
    name: 'Default'
    description: 'Creates a Cycloid organization'
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ project $)/pipeline/($ environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
