---
version: "2"
use_cases:
- name: default
  sections:
  - name: Cycloid Organization
    groups:
    - name: Organization
      technologies: [pipeline]
      vars:
      - name: "Organization Name"
        description: "Name of the Cycloid organization."
        key: organization_name
        widget: simple_text
        type: string
        default: ""
        required: true

    - name: Cycloid API
      technologies: [pipeline]
      vars:
      - name: "Cycloid API key"
        description: "API key to grant access to Cycloid API."
        key: cycloid_api_key
        widget: cy_cred
        type: string
        default: "((api-key-admin.key))"
        required: true

    - name: AWS Cloud Provider
      technologies: [pipeline]
      vars:
      - name: "AWS Account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "AWS Region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        default: eu-west-3
        required: true