version: "2"
name: NodeJS test stack from template
canonical: nodejs_test_stack_from_template
author: olivier
status: private
description: |
    Build and deploy a Node.js web application on an AWS EC2 instance.
image: |
    https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/node.svg
keywords:
    - cloud-init
    - user data
    - webapp
    - nodejs
    - nginx
    - provider:aws
template: true
technologies:
    - technology: nodejs
      version: ""
    - technology: nginx
      version: ""
dependencies: []
config:
    default:
        cloud_provider: aws
        description: Build and deploy a Node.js web application
        name: Default
        pipeline:
            pipeline:
                path: pipeline/pipeline.yaml
            variables:
                destination: ($ project $)/pipeline/($ environment $)/variables.yaml
                path: pipeline/variables.sample.yaml
        terraform:
            main:
                destination: ($ project $)/terraform/($ environment $)/main.tf
                path: terraform/main.tf
