---
# Configuration of the Cycloid stack
version: '2'
name: 'Azure Storage Account'
canonical: 'stack-azure-storage-rtf-poc'
description: This stack creates and manages an Azure Storage Account.
author: 'Olivier de Turckheim'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/azure-storage.svg'
status: 'private'
keywords:
- azure
- storage
- account
- container
- provider:azure
technologies:
- technology: azure
  version: "3.0.2"

config:
  default:
    name: 'Creates and manages an Azure Storage Account'
    # Pipeline and variable configuration for the Kubernetes pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
