version: "2"
name: Gitlab Pipeline
canonical: stack-gitlab-pipeline
status: private
author: Cycloid
description: |
  Triggers and manage deployments via a Gitlab pipeline.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/gitlab-ci.png
keywords:
  - gitlab
  - pipeline
technologies:
  - technology: gitlab

config:
  default:
    name: 'Default'
    description: 'Triggers and manage deployments via a Gitlab pipeline'
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ project $)/pipeline/($ environment $)/variables.yaml